### ISSUE TITLE
IRC commands have a longer than usual response time

### ISSUE THREAD

**Issue by ameliaikeda** [R-a-dio/Hanyuu-sama#54] opened 2012-12-27 19:15 UTC
Been noticing this a lot, recently, but hanyuu's `.lucky`, `.r` and `.np` commands seem to have excessive lag above what would be expected from IRC. Could do with some investigating.

**Comment by Wessie** [comment] 2012-12-27 19:20
I can't reproduce the `.lucky` and `.request` lags, the `.np` lag is due to streamstatus now being laggy most likely.

**Comment by Wessie** [comment] 2013-01-04 11:17
This was indeed caused by a slower `streamstatus` this has been mostly reduced and will be fully fixed in `1.3`.

**Closed as completed by Wessie** 2013-01-04 11:17 UTC
