### ISSUE TITLE
Hanyuu thinks she is streaming when she isnt

### ISSUE THREAD

**Issue by ameliaikeda** [R-a-dio/Hanyuu-sama#48] opened 2012-12-26 02:14 UTC
self explanatory. adding this to the stable milestone.
Comments about status and errors found below, please~

**Comment by Bevinsky** [comment] 2012-12-27 01:49
I do believe we have figure out why this happens. The bug occurs when a DJ disconnects, and then reconnects almost immediately after; Hanyuu detects the drop of the stream, thinks the stream is down and connects after the DJ already reconnects. So, the DJ is streaming to the real mountpoint, and Hanyuu is stuck on the proxy. Since Hanyuu sees a mountpoint on the Icecast status page, she thinks she's streaming, so she just keeps on going.

Hanyuu also kills the listener, so she starts feeding her own metadata into the system instead of what is actually being played.

One way of fixing this is to stop Hanyuu from taking the stream immediately after it drops, though there is still a possible race condition there. Another, better solution is to make Hanyuu aware of the proxy status instead of the Icecast status. Then she would be able to more directly see who exactly is streaming, as well.

Perhaps the proxy can call a method in Hanyuu's main manager to tell her if someone is streaming or not, and even give a DJ ID as well.

**Comment by Wessie** [comment] 2013-01-17 01:28
Instead of making Hanyuu aware of the proxy we can use a metadata comparison to check for this race condition.

If the metadata Hanyuu is streaming, and the metadata that is on the mount is not the same it can disconnect itself gracefully. We have to make sure the delay between metadata send and metadata show isn't caught in this case though.

**Comment by Bevinsky** [comment] 2013-01-17 02:48
I've actually been thinking, why doesn't Hanyuu make sure that someone is connected or not RIGHT before she connects, or at least has a slight delay before actually connecting after which she checks if someone picked up the stream again?

I think we should try to avoid the situation where she even starts her streamer completely. It messes up meta scraping. Or well, if we separate hanyuu and the listener, that isn't really an issue, but the listener should be really good at making sure Hanyuu doesn't connect at all, in my opinion.

**Comment by Wessie** [comment] 2013-03-05 03:35
Closed because we can't reproduce it anymore. This most likely got fixed in one of the various patches to the stream manager.

**Closed as completed by Wessie** 2013-03-05 03:35 UTC
Labels: bug

**Comment by Bevinsky** [comment] 2013-03-05 13:22
This got fixed because hanyuu doesn't connect if she isn't set as DJ. The bug will most likely still be there if she is given a chance.
